// export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
// export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
// export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
// export const ORDER_INFO_REQUEST = "ORDER_INFO_REQUEST";
// export const ORDER_INFO_SUCCESS = "ORDER_INFO_SUCCESS";
// export const ORDER_INFO_FAIL = "ORDER_INFO_FAIL";
